// Local custody of ride tracks: waypoints recorded on the rider's own device
// as sealed, HMAC-signed, hash-chained batches in IndexedDB. Nothing here
// touches the network and nothing here touches the DOM — the server sees no
// waypoint until the rider explicitly donates the chain at Screen 10.
//
// The wire format is normative and lives in `docs/RIDE_MODE_OVERHAUL_PLAN.md`
// Part 2, which is committed byte-identically to the API repo. Its byte-encoding
// rules are the whole ballgame, because the API's `src/track_verify.py` must
// hash exactly the same bytes:
//
//   * every sha256 input and intermediate value is RAW BYTES, never hex text;
//   * the nonce is HEX-DECODED to its 16 raw bytes before hashing;
//   * `sha256(jws_n)` is taken over the ASCII bytes of the compact JWS string;
//   * `prev` and `chain_root_hash` serialize as LOWERCASE HEX of the digest.
//
// Golden vectors proving this implementation agrees with the API's verifier
// live at `tests/fixtures/track-chain-vectors.json` — one file, the same
// literal path in both repos, regenerated by `scripts/gen-track-vectors.mjs`.
// If you change anything about sealing, signing or chaining, that fixture is
// the contract you are renegotiating with the API repo.

import type { DonateTrackIn, TrackSigning } from "./api.ts";

// ---------------------------------------------------------------------------
// Part 2 constants — normative. Do not "tune" these; the API caps and the
// golden vectors are both written against them.
// ---------------------------------------------------------------------------

export const TRACK_DB_NAME = "sfyi-tracks";
export const TRACK_DB_VERSION = 1;
export const TRACK_STORE_RIDES = "rides";
export const TRACK_STORE_BATCHES = "batches";
export const TRACK_STORE_PENDING = "pending";

/** Seal a batch at 25 waypoints … */
export const MAX_WAYPOINTS_PER_BATCH = 25;
/** … or 60 s, whichever comes first. A batch therefore always spans < 60 s:
 *  the fix that reaches the bound opens the NEXT batch rather than closing
 *  itself into the current one. */
export const MAX_BATCH_SPAN_MS = 60_000;

export const TRACK_JWS_ALG = "HS256";
export const TRACK_JWS_TYP = "sfyi-track+jws";
export const TRACK_PAYLOAD_VERSION = 1;

/** `rid` (and `kid`) for a private / guest ride: there is no `tracked_rides`
 *  row, no server-issued key and no points eligibility, so the ride identity
 *  in the payload is the literal `"private"` (master Part 2). Local records are
 *  keyed by a client-side `trackId` instead — see `startPrivateRide`. */
export const PRIVATE_RIDE_ID = "private";

/** Lat/lon are carried at 6 decimals and accuracy as an integer (Part 2). */
export const WAYPOINT_COORD_DECIMALS = 6;

/** Copy the UI shows when tracking fell back to memory (master Risk 9). Data,
 *  not DOM — this module renders nothing. */
export const TRACK_FALLBACK_WARNING =
  "Tracks won't survive a reload on this device — donate right after your ride.";

// ---------------------------------------------------------------------------
// Byte plumbing. Hand-rolled base64url rather than btoa/atob so the encoding
// is identical in a browser, in `node` and under happy-dom, with no reliance
// on a legacy global.
// ---------------------------------------------------------------------------

const B64URL_ALPHABET =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

const B64URL_LOOKUP: Record<string, number> = (() => {
  const map: Record<string, number> = {};
  for (let i = 0; i < B64URL_ALPHABET.length; i += 1) {
    map[B64URL_ALPHABET[i]] = i;
  }
  // Tolerate standard base64 too: the server sends base64url, but a `+`/`/`
  // key from any other producer should still import rather than throw.
  map["+"] = 62;
  map["/"] = 63;
  return map;
})();

/** Raw bytes. Pinned to `ArrayBuffer` rather than the default
 *  `ArrayBufferLike`, because `BufferSource` — what `crypto.subtle` takes —
 *  excludes a possibly-shared buffer. */
export type Bytes = Uint8Array<ArrayBuffer>;

const HEX_DIGITS = "0123456789abcdef";

export function bytesToHex(bytes: Uint8Array): string {
  let out = "";
  for (let i = 0; i < bytes.length; i += 1) {
    const b = bytes[i];
    out += HEX_DIGITS[b >> 4] + HEX_DIGITS[b & 0x0f];
  }
  return out;
}

const HEX_ONLY_RE = /^[0-9a-fA-F]*$/;

/** Hex → raw bytes. The nonce goes through here before it is ever hashed —
 *  hashing the hex *text* instead is the single most likely way for the two
 *  implementations to disagree, so this is deliberately explicit.
 *
 *  Validation is a whole-string regex rather than a per-byte `parseInt`:
 *  `parseInt` parses PREFIXES, so it quietly accepts `"1z"` as 0x01, `"-1"` as
 *  −1 (which a Uint8Array stores as 0xff) and `" 1"` as 0x01. Every one of those
 *  yields an `H_-1` the server cannot reproduce, with no local signal — the
 *  chain simply fails verification at donation. Throwing is the only honest
 *  outcome for a nonce we cannot decode. */
export function hexToBytes(hex: string): Bytes {
  if (hex.length % 2 !== 0) {
    throw new TrackStoreError("bad_hex", `odd-length hex string (${hex.length})`);
  }
  if (!HEX_ONLY_RE.test(hex)) {
    throw new TrackStoreError("bad_hex", `non-hex characters in ${hex}`);
  }
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i += 1) {
    out[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

export function base64UrlEncode(bytes: Uint8Array): string {
  let out = "";
  for (let i = 0; i < bytes.length; i += 3) {
    const b0 = bytes[i];
    const has1 = i + 1 < bytes.length;
    const has2 = i + 2 < bytes.length;
    const b1 = has1 ? bytes[i + 1] : 0;
    const b2 = has2 ? bytes[i + 2] : 0;
    out += B64URL_ALPHABET[b0 >> 2];
    out += B64URL_ALPHABET[((b0 & 0x03) << 4) | (b1 >> 4)];
    if (!has1) break;
    out += B64URL_ALPHABET[((b1 & 0x0f) << 2) | (b2 >> 6)];
    if (!has2) break;
    out += B64URL_ALPHABET[b2 & 0x3f];
  }
  return out;
}

export function base64UrlDecode(text: string): Bytes {
  const clean = text.replace(/=+$/, "");
  const out = new Uint8Array(Math.floor((clean.length * 6) / 8));
  let acc = 0;
  let bits = 0;
  let o = 0;
  for (const ch of clean) {
    const v = B64URL_LOOKUP[ch];
    if (v === undefined) {
      throw new TrackStoreError(
        "bad_base64url",
        `invalid base64url character ${JSON.stringify(ch)}`,
      );
    }
    acc = (acc << 6) | v;
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      out[o] = (acc >> bits) & 0xff;
      o += 1;
    }
  }
  return out;
}

const TEXT_ENCODER = new TextEncoder();

/** The compact JWS is ASCII by construction (base64url segments joined by
 *  dots), so UTF-8 encoding it *is* taking its ASCII bytes — Part 2's wording. */
export function asciiBytes(text: string): Bytes {
  return TEXT_ENCODER.encode(text);
}

export function concatBytes(a: Bytes, b: Bytes): Bytes {
  const out = new Uint8Array(a.length + b.length);
  out.set(a, 0);
  out.set(b, a.length);
  return out;
}

export async function sha256(bytes: Bytes): Promise<Bytes> {
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return new Uint8Array(digest);
}

// ---------------------------------------------------------------------------
// The chain (Part 2): H_-1 = sha256(nonce), H_n = sha256(H_{n-1} || sha256(jws_n))
// ---------------------------------------------------------------------------

/** `H_-1 = sha256(nonce)` — over the nonce's 16 RAW bytes, not its hex text. */
export function initialChainHash(nonceHex: string): Promise<Bytes> {
  return sha256(hexToBytes(nonceHex));
}

/** `sha256(jws_n)` as lowercase hex — this is what a successor batch carries
 *  in `prev`. */
export async function jwsHashHex(jws: string): Promise<string> {
  return bytesToHex(await sha256(asciiBytes(jws)));
}

/** `H_n = sha256(H_{n-1} || sha256(jws_n))`, all raw bytes. */
export async function advanceChainHash(
  previous: Bytes,
  jws: string,
): Promise<Bytes> {
  return sha256(concatBytes(previous, await sha256(asciiBytes(jws))));
}

/** Fold a whole chain to its `chain_root_hash`. The mirror of the server's
 *  check 2 recomputation, and what the golden-vector tests compare against. */
export async function recomputeChainRoot(
  nonceHex: string,
  jwsList: readonly string[],
): Promise<string> {
  let h = await initialChainHash(nonceHex);
  for (const jws of jwsList) h = await advanceChainHash(h, jws);
  return bytesToHex(h);
}

// ---------------------------------------------------------------------------
// Batch payloads + signing
// ---------------------------------------------------------------------------

/** `[dt_ms, lat, lon, acc_m]` — `dt_ms` relative to the batch's `t0`. */
export type WaypointTuple = [number, number, number, number];

export interface TrackJwsHeader {
  alg: typeof TRACK_JWS_ALG;
  typ: typeof TRACK_JWS_TYP;
  /** The ride id (`PRIVATE_RIDE_ID` for a private ride). */
  kid: string;
}

export interface TrackBatchPayload {
  v: typeof TRACK_PAYLOAD_VERSION;
  rid: string;
  non: string;
  seq: number;
  /** Lowercase hex sha256 of the predecessor's compact JWS; `""` at seq 0. */
  prev: string;
  t0: number;
  t1: number;
  pts: WaypointTuple[];
  /** True when the batch was sealed from crash-recovered unsealed points. */
  rec: boolean;
}

// Both JSON objects are built with their keys in the exact order Part 2 lists
// them, and JSON.stringify preserves insertion order for non-index keys — that
// is what makes the compact JWS byte-reproducible across runs and across the
// independent generator in scripts/gen-track-vectors.mjs.
function headerJson(kid: string): string {
  const header: TrackJwsHeader = {
    alg: TRACK_JWS_ALG,
    typ: TRACK_JWS_TYP,
    kid,
  };
  return JSON.stringify(header);
}

function payloadJson(payload: TrackBatchPayload): string {
  return JSON.stringify({
    v: payload.v,
    rid: payload.rid,
    non: payload.non,
    seq: payload.seq,
    prev: payload.prev,
    t0: payload.t0,
    t1: payload.t1,
    pts: payload.pts,
    rec: payload.rec,
  });
}

/** Seal one batch into a compact JWS (`header.payload.mac`, HS256). */
export async function signTrackBatch(
  key: CryptoKey,
  kid: string,
  payload: TrackBatchPayload,
): Promise<string> {
  const signingInput = `${base64UrlEncode(
    asciiBytes(headerJson(kid)),
  )}.${base64UrlEncode(asciiBytes(payloadJson(payload)))}`;
  const mac = await crypto.subtle.sign("HMAC", key, asciiBytes(signingInput));
  return `${signingInput}.${base64UrlEncode(new Uint8Array(mac))}`;
}

/** Decode a compact JWS's payload without verifying it. Local reads only —
 *  the client is the key holder, so this proves nothing; the server verifies. */
export function decodeTrackBatch(jws: string): TrackBatchPayload {
  const parts = jws.split(".");
  if (parts.length !== 3) {
    throw new TrackStoreError("bad_jws", `expected 3 JWS segments, got ${parts.length}`);
  }
  const text = new TextDecoder().decode(base64UrlDecode(parts[1]));
  return JSON.parse(text) as TrackBatchPayload;
}

const HMAC_PARAMS: HmacImportParams = { name: "HMAC", hash: "SHA-256" };

/** Import the server-issued per-ride key. `extractable: false` is hygiene, not
 *  a security boundary — for a server ride the raw key is re-fetchable from
 *  `GET /tracked-rides/active`.`track_signing` anyway; it just keeps raw key
 *  bytes out of JS reach at rest. */
export function importTrackKey(keyB64Url: string): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    "raw",
    base64UrlDecode(keyB64Url),
    HMAC_PARAMS,
    false,
    ["sign"],
  );
}

/** Client-random key for a private / guest ride: tamper-evident only, never
 *  points-eligible, never uploaded. */
export function generateTrackKey(): Promise<CryptoKey> {
  return crypto.subtle.generateKey(
    { name: "HMAC", hash: "SHA-256", length: 256 },
    false,
    ["sign"],
  ) as Promise<CryptoKey>;
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

export type TrackStoreErrorCode =
  | "bad_hex"
  | "bad_base64url"
  | "bad_jws"
  | "missing_signing"
  | "private_ride"
  | "storage";

export class TrackStoreError extends Error {
  readonly code: TrackStoreErrorCode;
  constructor(code: TrackStoreErrorCode, message: string) {
    super(message);
    this.name = "TrackStoreError";
    this.code = code;
  }
}

// ---------------------------------------------------------------------------
// Storage adapter. Two implementations: IndexedDB (`sfyi-tracks`) and an
// in-memory fallback for private mode / no-IDB browsers. The interface exists
// so the recorder is unit-testable without a fake IDB, and so the eviction
// paths recovery has to handle can be provoked deterministically.
// ---------------------------------------------------------------------------

export interface StoredTrackRide {
  /** Primary key. Equals the `rideId` for a server ride (so the recovery
   *  table's "batches store keyed by rideId" reads literally); a
   *  `private-<hex>` local id for a private ride. */
  trackId: string;
  rideId: string | null;
  private: boolean;
  /** Hex, 16 bytes. */
  nonce: string;
  /** Payload `rid` — the ride id, or `PRIVATE_RIDE_ID`. */
  rid: string;
  /** Protected-header `kid` — the same value as `rid`. */
  kid: string;
  key: CryptoKey;
  createdAtMs: number;
  // ----- chain tip, mirrored here so a resume is O(1). The `batches` store
  // stays authoritative: it is what gets uploaded, so `readTip` derives from
  // it and this mirror is only a cross-check.
  nextSeq: number;
  prevJwsHash: string;
  chainHash: string;
  batchCount: number;
  waypointCount: number;
  lastPointMs: number | null;
}

export interface StoredTrackBatch {
  trackId: string;
  seq: number;
  /** The compact JWS — the only thing donation uploads. */
  jws: string;
  /** Lowercase hex `sha256(jws)`; the successor's `prev`. */
  jwsHash: string;
  /** Lowercase hex `H_n` after this batch. */
  chainHash: string;
  t0: number;
  t1: number;
  count: number;
  rec: boolean;
}

export interface StoredPendingBatch {
  trackId: string;
  t0: number;
  points: WaypointTuple[];
  lastPointMs: number;
}

export interface TrackStorage {
  /** False for the in-memory fallback — the UI's warning flag. */
  readonly durable: boolean;
  putRide(ride: StoredTrackRide): Promise<void>;
  getRide(trackId: string): Promise<StoredTrackRide | null>;
  listRides(): Promise<StoredTrackRide[]>;
  getBatches(trackId: string): Promise<StoredTrackBatch[]>;
  /** Atomic seal: append the batch, advance the ride's chain tip and drop the
   *  pending open batch in ONE transaction. Doing these as three writes would
   *  let a crash in the middle replay already-sealed points as a `rec:true`
   *  batch and double-count them. */
  commitSeal(batch: StoredTrackBatch, ride: StoredTrackRide): Promise<void>;
  putPending(pending: StoredPendingBatch): Promise<void>;
  getPending(trackId: string): Promise<StoredPendingBatch | null>;
  deletePending(trackId: string): Promise<void>;
  deleteRide(trackId: string): Promise<void>;
}

export class MemoryTrackStorage implements TrackStorage {
  readonly durable = false;
  private readonly rides = new Map<string, StoredTrackRide>();
  private readonly batches = new Map<string, Map<number, StoredTrackBatch>>();
  private readonly pending = new Map<string, StoredPendingBatch>();

  async putRide(ride: StoredTrackRide): Promise<void> {
    this.rides.set(ride.trackId, { ...ride });
  }

  async getRide(trackId: string): Promise<StoredTrackRide | null> {
    const found = this.rides.get(trackId);
    return found ? { ...found } : null;
  }

  async listRides(): Promise<StoredTrackRide[]> {
    return [...this.rides.values()].map((r) => ({ ...r }));
  }

  async getBatches(trackId: string): Promise<StoredTrackBatch[]> {
    const bySeq = this.batches.get(trackId);
    if (!bySeq) return [];
    return [...bySeq.values()]
      .map((b) => ({ ...b }))
      .sort((a, b) => a.seq - b.seq);
  }

  async commitSeal(
    batch: StoredTrackBatch,
    ride: StoredTrackRide,
  ): Promise<void> {
    let bySeq = this.batches.get(batch.trackId);
    if (!bySeq) {
      bySeq = new Map();
      this.batches.set(batch.trackId, bySeq);
    }
    bySeq.set(batch.seq, { ...batch });
    this.rides.set(ride.trackId, { ...ride });
    this.pending.delete(batch.trackId);
  }

  async putPending(pending: StoredPendingBatch): Promise<void> {
    this.pending.set(pending.trackId, {
      ...pending,
      points: pending.points.map((p) => [...p] as WaypointTuple),
    });
  }

  async getPending(trackId: string): Promise<StoredPendingBatch | null> {
    const found = this.pending.get(trackId);
    return found
      ? { ...found, points: found.points.map((p) => [...p] as WaypointTuple) }
      : null;
  }

  async deletePending(trackId: string): Promise<void> {
    this.pending.delete(trackId);
  }

  async deleteRide(trackId: string): Promise<void> {
    this.rides.delete(trackId);
    this.batches.delete(trackId);
    this.pending.delete(trackId);
  }
}

function idbRequest<T>(request: IDBRequest<T>): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    request.onsuccess = () => resolve(request.result);
    request.onerror = () =>
      reject(
        new TrackStoreError(
          "storage",
          request.error?.message ?? "IndexedDB request failed",
        ),
      );
  });
}

function idbTxDone(tx: IDBTransaction): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    tx.oncomplete = () => resolve();
    tx.onabort = tx.onerror = () =>
      reject(
        new TrackStoreError(
          "storage",
          tx.error?.message ?? "IndexedDB transaction aborted",
        ),
      );
  });
}

export class IdbTrackStorage implements TrackStorage {
  readonly durable = true;
  private readonly db: IDBDatabase;

  constructor(db: IDBDatabase) {
    this.db = db;
  }

  static open(factory: IDBFactory): Promise<IdbTrackStorage> {
    return new Promise<IdbTrackStorage>((resolve, reject) => {
      const request = factory.open(TRACK_DB_NAME, TRACK_DB_VERSION);
      request.onupgradeneeded = () => {
        const db = request.result;
        if (!db.objectStoreNames.contains(TRACK_STORE_RIDES)) {
          db.createObjectStore(TRACK_STORE_RIDES, { keyPath: "trackId" });
        }
        if (!db.objectStoreNames.contains(TRACK_STORE_BATCHES)) {
          const batches = db.createObjectStore(TRACK_STORE_BATCHES, {
            keyPath: ["trackId", "seq"],
          });
          batches.createIndex("trackId", "trackId", { unique: false });
        }
        if (!db.objectStoreNames.contains(TRACK_STORE_PENDING)) {
          db.createObjectStore(TRACK_STORE_PENDING, { keyPath: "trackId" });
        }
      };
      request.onsuccess = () => resolve(new IdbTrackStorage(request.result));
      request.onerror = () =>
        reject(
          new TrackStoreError(
            "storage",
            request.error?.message ?? "could not open IndexedDB",
          ),
        );
      request.onblocked = () =>
        reject(new TrackStoreError("storage", "IndexedDB open blocked"));
    });
  }

  private async write(
    stores: string[],
    body: (tx: IDBTransaction) => void,
  ): Promise<void> {
    const tx = this.db.transaction(stores, "readwrite");
    const done = idbTxDone(tx);
    body(tx);
    await done;
  }

  async putRide(ride: StoredTrackRide): Promise<void> {
    await this.write([TRACK_STORE_RIDES], (tx) => {
      tx.objectStore(TRACK_STORE_RIDES).put(ride);
    });
  }

  async getRide(trackId: string): Promise<StoredTrackRide | null> {
    const tx = this.db.transaction([TRACK_STORE_RIDES], "readonly");
    const row = await idbRequest<StoredTrackRide | undefined>(
      tx.objectStore(TRACK_STORE_RIDES).get(trackId),
    );
    return row ?? null;
  }

  async listRides(): Promise<StoredTrackRide[]> {
    const tx = this.db.transaction([TRACK_STORE_RIDES], "readonly");
    return idbRequest<StoredTrackRide[]>(
      tx.objectStore(TRACK_STORE_RIDES).getAll(),
    );
  }

  async getBatches(trackId: string): Promise<StoredTrackBatch[]> {
    const tx = this.db.transaction([TRACK_STORE_BATCHES], "readonly");
    const rows = await idbRequest<StoredTrackBatch[]>(
      tx.objectStore(TRACK_STORE_BATCHES).index("trackId").getAll(trackId),
    );
    return rows.sort((a, b) => a.seq - b.seq);
  }

  async commitSeal(
    batch: StoredTrackBatch,
    ride: StoredTrackRide,
  ): Promise<void> {
    await this.write(
      [TRACK_STORE_BATCHES, TRACK_STORE_RIDES, TRACK_STORE_PENDING],
      (tx) => {
        tx.objectStore(TRACK_STORE_BATCHES).put(batch);
        tx.objectStore(TRACK_STORE_RIDES).put(ride);
        tx.objectStore(TRACK_STORE_PENDING).delete(batch.trackId);
      },
    );
  }

  async putPending(pending: StoredPendingBatch): Promise<void> {
    await this.write([TRACK_STORE_PENDING], (tx) => {
      tx.objectStore(TRACK_STORE_PENDING).put(pending);
    });
  }

  async getPending(trackId: string): Promise<StoredPendingBatch | null> {
    const tx = this.db.transaction([TRACK_STORE_PENDING], "readonly");
    const row = await idbRequest<StoredPendingBatch | undefined>(
      tx.objectStore(TRACK_STORE_PENDING).get(trackId),
    );
    return row ?? null;
  }

  async deletePending(trackId: string): Promise<void> {
    await this.write([TRACK_STORE_PENDING], (tx) => {
      tx.objectStore(TRACK_STORE_PENDING).delete(trackId);
    });
  }

  async deleteRide(trackId: string): Promise<void> {
    const batches = await this.getBatches(trackId);
    await this.write(
      [TRACK_STORE_RIDES, TRACK_STORE_BATCHES, TRACK_STORE_PENDING],
      (tx) => {
        tx.objectStore(TRACK_STORE_RIDES).delete(trackId);
        const store = tx.objectStore(TRACK_STORE_BATCHES);
        for (const b of batches) store.delete([trackId, b.seq]);
        tx.objectStore(TRACK_STORE_PENDING).delete(trackId);
      },
    );
  }
}

// ---------------------------------------------------------------------------
// The recorder
// ---------------------------------------------------------------------------

/** One GPS fix as the HUD's shared `watchPosition` hands it over. */
export interface TrackFix {
  /** Epoch ms — `GeolocationPosition.timestamp`. */
  tMs: number;
  lat: number;
  lon: number;
  /** `coords.accuracy` in metres. Unknown becomes 0, never a large number:
   *  the server SUBTRACTS accuracy from segment distance before the speed
   *  check, so inflating it would be gaming our own rider's chain. */
  accM?: number | null;
}

export type TrackFixRejection =
  | "not_recording"
  | "non_monotonic"
  | "invalid_fix";

export interface TrackAddResult {
  accepted: boolean;
  rejected: TrackFixRejection | null;
  /** The batch this fix's arrival sealed (the 25-waypoint or 60-second rule). */
  sealed: StoredTrackBatch | null;
  /** Unsealed points held in the `pending` store after this call. */
  openCount: number;
}

export interface TrackFinishResult {
  /** The final partial batch, or null when nothing was open. */
  sealed: StoredTrackBatch | null;
  batchCount: number;
  waypointCount: number;
  chainRootHash: string | null;
}

export interface TrackTip {
  trackId: string;
  /** The seq the NEXT sealed batch will carry. */
  nextSeq: number;
  /** `prev` for the next batch — `""` when nothing is sealed yet. */
  prevJwsHash: string;
  /** Lowercase hex `H_n` of the last sealed batch, or `H_-1` when none. */
  chainHash: string;
  batchCount: number;
  waypointCount: number;
  /** Unsealed points still sitting in the `pending` store. They WILL become a
   *  `rec:true` batch on resume, so "were any waypoints recorded?" is
   *  `waypointCount + pendingCount`, not `waypointCount` alone. */
  pendingCount: number;
  /** `t1` of the last sealed batch (or the newest pending point). */
  lastPointMs: number | null;
}

export interface TrackSessionInfo extends TrackTip {
  rideId: string | null;
  private: boolean;
  nonce: string;
  recording: boolean;
  durable: boolean;
  openCount: number;
  /** Lowercase hex `H_n`, or null before the first seal. */
  chainRootHash: string | null;
}

interface OpenBatch {
  t0: number;
  lastMs: number;
  points: WaypointTuple[];
}

function roundCoord(value: number): number {
  // toFixed then re-parse: the shortest round-tripping double for an exact
  // 6-decimal value, which is what JSON.stringify then emits. Doing the same
  // arithmetic in the fixture generator is why the two agree byte-for-byte.
  return Number(value.toFixed(WAYPOINT_COORD_DECIMALS));
}

function roundAccuracy(accM: number | null | undefined): number {
  if (accM === null || accM === undefined || !Number.isFinite(accM)) return 0;
  return Math.max(0, Math.round(accM));
}

/** Records one ride's track. Serialized internally: every mutating call joins
 *  a promise chain, so a burst of fixes can never interleave two seals and
 *  skip a `seq`. */
export class TrackRecorder {
  readonly trackId: string;
  readonly rideId: string | null;
  readonly isPrivate: boolean;
  readonly nonce: string;

  private readonly storage: TrackStorage;
  private readonly key: CryptoKey;
  private readonly rid: string;
  private readonly kid: string;
  private readonly createdAtMs: number;

  private nextSeq: number;
  private prevJwsHash: string;
  private chainHash: Bytes;
  private batchCount: number;
  private waypointCount: number;
  private lastPointMs: number | null;
  private open: OpenBatch | null = null;
  private recording = true;
  private queue: Promise<unknown> = Promise.resolve();

  constructor(init: {
    storage: TrackStorage;
    ride: StoredTrackRide;
    tip: TrackTip;
    open: OpenBatch | null;
    chainHash: Bytes;
  }) {
    this.storage = init.storage;
    this.trackId = init.ride.trackId;
    this.rideId = init.ride.rideId;
    this.isPrivate = init.ride.private;
    this.nonce = init.ride.nonce;
    this.key = init.ride.key;
    this.rid = init.ride.rid;
    this.kid = init.ride.kid;
    this.createdAtMs = init.ride.createdAtMs;
    this.nextSeq = init.tip.nextSeq;
    this.prevJwsHash = init.tip.prevJwsHash;
    this.chainHash = init.chainHash;
    this.batchCount = init.tip.batchCount;
    this.waypointCount = init.tip.waypointCount;
    this.lastPointMs = init.tip.lastPointMs;
    this.open = init.open;
  }

  get durable(): boolean {
    return this.storage.durable;
  }

  /** Lowercase hex `H_n`, or null before the first seal — what donation
   *  reports as `chain_root_hash`. */
  get chainRootHash(): string | null {
    return this.batchCount > 0 ? bytesToHex(this.chainHash) : null;
  }

  get isRecording(): boolean {
    return this.recording;
  }

  info(): TrackSessionInfo {
    return {
      trackId: this.trackId,
      rideId: this.rideId,
      private: this.isPrivate,
      nonce: this.nonce,
      nextSeq: this.nextSeq,
      prevJwsHash: this.prevJwsHash,
      chainHash: bytesToHex(this.chainHash),
      chainRootHash: this.chainRootHash,
      batchCount: this.batchCount,
      waypointCount: this.waypointCount,
      // The in-memory open batch IS what the `pending` store holds, so these
      // two are the same number by construction.
      pendingCount: this.open?.points.length ?? 0,
      lastPointMs: this.lastPointMs,
      recording: this.recording,
      durable: this.storage.durable,
      openCount: this.open?.points.length ?? 0,
    };
  }

  /** Record one fix. Rejects a non-advancing timestamp rather than writing it:
   *  the API's check 3 requires strictly increasing timestamps across the
   *  flattened track, and a duplicated or back-dated GPS sample would fail the
   *  whole chain. Dropping a duplicate is deduplication, not fabrication. */
  addFix(fix: TrackFix): Promise<TrackAddResult> {
    return this.run(() => this.addFixLocked(fix));
  }

  /** Seal whatever is open. `rec` marks a batch rebuilt from crash-recovered
   *  points. Returns null when nothing was open. */
  sealOpenBatch(opts: { rec?: boolean } = {}): Promise<StoredTrackBatch | null> {
    return this.run(() => this.sealLocked(opts.rec === true));
  }

  /** Ride end (or the wrench's "Stop tracking"): seal the final partial batch
   *  and stop accepting fixes. Idempotent. */
  finish(): Promise<TrackFinishResult> {
    return this.run(async () => {
      // Recording stops even if the final seal's write fails: the ride IS over,
      // and the unsealed points stay in the `pending` store, so a later resume
      // still seals them as a `rec:true` batch. The rejection reaches the caller
      // either way, and calling `finish()` again retries the seal.
      let sealed: StoredTrackBatch | null;
      try {
        sealed = await this.sealLocked(false);
      } finally {
        this.recording = false;
      }
      return {
        sealed,
        batchCount: this.batchCount,
        waypointCount: this.waypointCount,
        chainRootHash: this.chainRootHash,
      };
    });
  }

  /** Crash recovery: adopt unsealed points left in the `pending` store and
   *  seal them immediately as a `rec:true` batch. Called by `resumeRide`
   *  before any new fix is accepted, so the recovered points keep their
   *  original place in the chain. */
  adoptPending(pending: StoredPendingBatch): Promise<StoredTrackBatch | null> {
    return this.run(async () => {
      if (this.open) return null;
      const points = pending.points.map((p) => [...p] as WaypointTuple);
      if (points.length === 0) return null;
      this.open = {
        t0: pending.t0,
        lastMs: pending.lastPointMs,
        points,
      };
      return this.sealLocked(true);
    });
  }

  /** Every sealed batch, seq-ordered — the donation body's `batches`. */
  batches(): Promise<StoredTrackBatch[]> {
    return this.run(() => this.storage.getBatches(this.trackId));
  }

  /** `POST /tracked-rides/{id}/track`'s body. One request, no chunking. */
  async buildDonation(): Promise<DonateTrackIn> {
    if (this.isPrivate) {
      throw new TrackStoreError(
        "private_ride",
        "a private ride's chain is signed with a client-random key and is never donatable",
      );
    }
    const batches = await this.batches();
    const body: DonateTrackIn = { batches: batches.map((b) => b.jws) };
    const root = batches.length ? batches[batches.length - 1].chainHash : null;
    if (root) body.chain_root_hash = root;
    return body;
  }

  /** Wipe this ride's local track. Donation is opt-in; this is the "never
   *  mind" path, and the only way waypoints leave the device is a donation. */
  discard(): Promise<void> {
    return this.run(async () => {
      this.recording = false;
      this.open = null;
      await this.storage.deleteRide(this.trackId);
    });
  }

  // ----- internals

  private run<T>(fn: () => Promise<T>): Promise<T> {
    const next = this.queue.then(fn, fn);
    this.queue = next.then(
      () => undefined,
      () => undefined,
    );
    return next;
  }

  private async addFixLocked(fix: TrackFix): Promise<TrackAddResult> {
    if (!this.recording) {
      return {
        accepted: false,
        rejected: "not_recording",
        sealed: null,
        openCount: this.open?.points.length ?? 0,
      };
    }
    if (
      !Number.isFinite(fix.tMs) ||
      !Number.isFinite(fix.lat) ||
      !Number.isFinite(fix.lon) ||
      Math.abs(fix.lat) > 90 ||
      Math.abs(fix.lon) > 180
    ) {
      return {
        accepted: false,
        rejected: "invalid_fix",
        sealed: null,
        openCount: this.open?.points.length ?? 0,
      };
    }
    const tMs = Math.round(fix.tMs);
    const newest = this.open ? this.open.lastMs : this.lastPointMs;
    if (newest !== null && tMs <= newest) {
      return {
        accepted: false,
        rejected: "non_monotonic",
        sealed: null,
        openCount: this.open?.points.length ?? 0,
      };
    }

    // The 60-second rule: the fix that reaches the bound opens the NEXT batch,
    // so a sealed batch always spans strictly less than MAX_BATCH_SPAN_MS.
    let sealed: StoredTrackBatch | null = null;
    if (this.open && tMs - this.open.t0 >= MAX_BATCH_SPAN_MS) {
      sealed = await this.sealLocked(false);
    }
    if (!this.open) this.open = { t0: tMs, lastMs: tMs, points: [] };

    this.open.points.push([
      tMs - this.open.t0,
      roundCoord(fix.lat),
      roundCoord(fix.lon),
      roundAccuracy(fix.accM),
    ]);
    this.open.lastMs = tMs;
    await this.storage.putPending({
      trackId: this.trackId,
      t0: this.open.t0,
      points: this.open.points,
      lastPointMs: this.open.lastMs,
    });

    // The 25-waypoint rule: a full batch seals immediately, so it never waits
    // on the next fix (which may never come — a ride can end here).
    if (this.open.points.length >= MAX_WAYPOINTS_PER_BATCH) {
      sealed = await this.sealLocked(false);
    }
    return {
      accepted: true,
      rejected: null,
      sealed,
      openCount: this.open?.points.length ?? 0,
    };
  }

  private async sealLocked(rec: boolean): Promise<StoredTrackBatch | null> {
    const open = this.open;
    if (!open || open.points.length === 0) return null;
    const payload: TrackBatchPayload = {
      v: TRACK_PAYLOAD_VERSION,
      rid: this.rid,
      non: this.nonce,
      seq: this.nextSeq,
      prev: this.prevJwsHash,
      t0: open.t0,
      t1: open.lastMs,
      pts: open.points,
      rec,
    };
    const jws = await signTrackBatch(this.key, this.kid, payload);
    const jwsDigest = await sha256(asciiBytes(jws));
    const chainHash = await sha256(concatBytes(this.chainHash, jwsDigest));
    const batch: StoredTrackBatch = {
      trackId: this.trackId,
      seq: this.nextSeq,
      jws,
      jwsHash: bytesToHex(jwsDigest),
      chainHash: bytesToHex(chainHash),
      t0: payload.t0,
      t1: payload.t1,
      count: open.points.length,
      rec,
    };

    // The ride row committed alongside the batch describes the POST-seal tip
    // (one atomic write), but the recorder's own tip only moves once that write
    // has landed. Advancing first would make a single transient IndexedDB
    // failure permanent and silent: seq would already have skipped past a batch
    // that never reached the store, so the donated chain would be
    // non-contiguous and fail the API's check 2 as `chain_invalid` — with the
    // rider's points lost for a write they never saw fail. Leaving the batch
    // open instead means the next fix (or `finish()`) simply re-seals it.
    const post = this.tipAfter(batch, chainHash);
    await this.storage.commitSeal(batch, post);
    this.nextSeq = post.nextSeq;
    this.prevJwsHash = post.prevJwsHash;
    this.chainHash = chainHash;
    this.batchCount = post.batchCount;
    this.waypointCount = post.waypointCount;
    this.lastPointMs = post.lastPointMs;
    this.open = null;
    return batch;
  }

  /** The ride record as it will read once `batch` is sealed. Pure — it reads
   *  `this` but mutates nothing, which is what lets the commit happen before
   *  the recorder moves. */
  private tipAfter(batch: StoredTrackBatch, chainHash: Bytes): StoredTrackRide {
    return {
      trackId: this.trackId,
      rideId: this.rideId,
      private: this.isPrivate,
      nonce: this.nonce,
      rid: this.rid,
      kid: this.kid,
      key: this.key,
      createdAtMs: this.createdAtMs,
      nextSeq: batch.seq + 1,
      prevJwsHash: batch.jwsHash,
      chainHash: bytesToHex(chainHash),
      batchCount: this.batchCount + 1,
      waypointCount: this.waypointCount + batch.count,
      lastPointMs: batch.t1,
    };
  }
}

// ---------------------------------------------------------------------------
// Store: open once per page, then start / resume per ride.
// ---------------------------------------------------------------------------

export type TrackStoreWarning =
  /** No IndexedDB at all (Safari private mode, some embedded webviews). */
  | "no_indexeddb"
  /** IndexedDB exists but `open()` failed, was blocked, or the DB was evicted
   *  and re-created empty. */
  | "indexeddb_failed";

export interface TrackStoreOptions {
  /** Inject a storage adapter — tests use `MemoryTrackStorage` directly. */
  storage?: TrackStorage;
  /** Defaults to `globalThis.indexedDB`; pass null to force the fallback. */
  indexedDBFactory?: IDBFactory | null;
  now?: () => number;
  randomBytes?: (n: number) => Bytes;
  /** Private/guest rides normally use `crypto.subtle.generateKey`; tests
   *  inject a deterministic key instead. */
  generatePrivateKey?: () => Promise<CryptoKey>;
}

export interface TrackResumeOptions {
  /** `active.track_signing` — lets a resume re-import the key after the local
   *  record was evicted. */
  signing?: TrackSigning | null;
  /** Resume a private ride, which has no server signing material to fall back
   *  on: an evicted record means a new chain under a new client-random key. */
  isPrivate?: boolean;
}

export interface TrackResume {
  recorder: TrackRecorder;
  /** True when sealed batches survived locally and the recorder continues that
   *  chain from its tip. */
  continued: boolean;
  /** True when nothing survived and recording restarts at `seq 0` / `prev: ""`.
   *  The recovery table's honest path: never pretend the pre-eviction track is
   *  intact — donate what survives and let server validation adjudicate. */
  freshChain: boolean;
  keySource: "idb" | "server" | "generated";
  /** The `rec:true` batch sealed from crash-recovered unsealed points. */
  recovered: StoredTrackBatch | null;
  tip: TrackTip;
}

export interface TrackStore {
  readonly durable: boolean;
  readonly warning: TrackStoreWarning | null;
  readonly storage: TrackStorage;
  startServerRide(signing: TrackSigning): Promise<TrackRecorder>;
  startPrivateRide(): Promise<TrackRecorder>;
  resumeRide(trackId: string, opts?: TrackResumeOptions): Promise<TrackResume>;
  /** The chain tip as the recovery table needs it, derived from the `batches`
   *  store (authoritative) — null when this device knows nothing about the
   *  ride. */
  readTip(trackId: string): Promise<TrackTip | null>;
  listTrackIds(): Promise<string[]>;
  deleteRide(trackId: string): Promise<void>;
}

const DEFAULT_RANDOM_BYTES = (n: number): Bytes =>
  crypto.getRandomValues(new Uint8Array(n));

class TrackStoreImpl implements TrackStore {
  readonly storage: TrackStorage;
  readonly warning: TrackStoreWarning | null;
  private readonly now: () => number;
  private readonly randomBytes: (n: number) => Bytes;
  private readonly generatePrivateKey: () => Promise<CryptoKey>;

  constructor(
    storage: TrackStorage,
    warning: TrackStoreWarning | null,
    opts: TrackStoreOptions,
  ) {
    this.storage = storage;
    this.warning = warning;
    this.now = opts.now ?? (() => Date.now());
    this.randomBytes = opts.randomBytes ?? DEFAULT_RANDOM_BYTES;
    this.generatePrivateKey = opts.generatePrivateKey ?? generateTrackKey;
  }

  get durable(): boolean {
    return this.storage.durable;
  }

  async startServerRide(signing: TrackSigning): Promise<TrackRecorder> {
    const rideId = signing.key_id;
    const ride: StoredTrackRide = {
      trackId: rideId,
      rideId,
      private: false,
      nonce: signing.nonce,
      rid: rideId,
      kid: rideId,
      key: await importTrackKey(signing.key),
      createdAtMs: this.now(),
      nextSeq: 0,
      prevJwsHash: "",
      chainHash: bytesToHex(await initialChainHash(signing.nonce)),
      batchCount: 0,
      waypointCount: 0,
      lastPointMs: null,
    };
    return this.begin(ride);
  }

  async startPrivateRide(): Promise<TrackRecorder> {
    const nonce = bytesToHex(this.randomBytes(16));
    const ride: StoredTrackRide = {
      trackId: `${PRIVATE_RIDE_ID}-${bytesToHex(this.randomBytes(6))}`,
      rideId: null,
      private: true,
      nonce,
      // No tracked_rides row exists, so the payload's ride identity is the
      // literal "private" (master Part 2) and the header's kid matches it.
      // Local records are told apart by `trackId`, not by kid.
      rid: PRIVATE_RIDE_ID,
      kid: PRIVATE_RIDE_ID,
      key: await this.generatePrivateKey(),
      createdAtMs: this.now(),
      nextSeq: 0,
      prevJwsHash: "",
      chainHash: bytesToHex(await initialChainHash(nonce)),
      batchCount: 0,
      waypointCount: 0,
      lastPointMs: null,
    };
    return this.begin(ride);
  }

  private async begin(ride: StoredTrackRide): Promise<TrackRecorder> {
    await this.storage.putRide(ride);
    await this.storage.deletePending(ride.trackId);
    return new TrackRecorder({
      storage: this.storage,
      ride,
      tip: {
        trackId: ride.trackId,
        nextSeq: 0,
        prevJwsHash: "",
        chainHash: ride.chainHash,
        batchCount: 0,
        waypointCount: 0,
        pendingCount: 0,
        lastPointMs: null,
      },
      open: null,
      chainHash: hexToBytes(ride.chainHash),
    });
  }

  async readTip(trackId: string): Promise<TrackTip | null> {
    const [ride, batches, pending] = await Promise.all([
      this.storage.getRide(trackId),
      this.storage.getBatches(trackId),
      this.storage.getPending(trackId),
    ]);
    if (!ride && batches.length === 0) return null;
    return tipFromBatches(trackId, batches, ride, pending);
  }

  async resumeRide(
    trackId: string,
    opts: TrackResumeOptions = {},
  ): Promise<TrackResume> {
    const stored = await this.storage.getRide(trackId);
    const batches = await this.storage.getBatches(trackId);
    const signing = opts.signing ?? null;

    let ride: StoredTrackRide | null = stored;
    let keySource: TrackResume["keySource"] = "idb";
    if (!ride) {
      // The local record is gone. Two honest outcomes, and neither pretends
      // the pre-eviction chain survived: re-import the server key (a server
      // ride) or mint a new client-random one (a private ride).
      if (signing) {
        keySource = "server";
        ride = {
          trackId,
          rideId: signing.key_id,
          private: false,
          nonce: signing.nonce,
          rid: signing.key_id,
          kid: signing.key_id,
          key: await importTrackKey(signing.key),
          createdAtMs: this.now(),
          nextSeq: 0,
          prevJwsHash: "",
          chainHash: bytesToHex(await initialChainHash(signing.nonce)),
          batchCount: 0,
          waypointCount: 0,
          lastPointMs: null,
        };
      } else if (opts.isPrivate) {
        keySource = "generated";
        const nonce = bytesToHex(this.randomBytes(16));
        ride = {
          trackId,
          rideId: null,
          private: true,
          nonce,
          rid: PRIVATE_RIDE_ID,
          kid: PRIVATE_RIDE_ID,
          key: await this.generatePrivateKey(),
          createdAtMs: this.now(),
          nextSeq: 0,
          prevJwsHash: "",
          chainHash: bytesToHex(await initialChainHash(nonce)),
          batchCount: 0,
          waypointCount: 0,
          lastPointMs: null,
        };
      } else {
        throw new TrackStoreError(
          "missing_signing",
          `no local track for ${trackId} and no track_signing to re-import`,
        );
      }
      await this.storage.putRide(ride);
    }

    // Batches only continue a chain when they were signed under the SAME
    // nonce; a re-imported key with a rotated nonce is a different chain.
    const stale =
      batches.length > 0 && !batchesMatchNonce(batches, ride.nonce);
    const usable = stale ? [] : batches;
    if (stale) {
      // Wipe the old generation outright. Splicing two chains together is
      // obviously wrong, but so is leaving it in place: the new chain restarts
      // at seq 0 and would only overwrite the old batches it collides with,
      // leaving higher-seq orphans for a later donation to upload.
      await this.storage.deleteRide(trackId);
      await this.storage.putRide(ride);
    }
    const tip = tipFromBatches(trackId, usable, ride, null);
    const recorder = new TrackRecorder({
      storage: this.storage,
      ride: { ...ride, ...tipFields(tip) },
      tip,
      open: null,
      chainHash: hexToBytes(tip.chainHash),
    });

    // Crash mid-batch: replay the `pending` store and seal it as `rec:true`.
    let recovered: StoredTrackBatch | null = null;
    const pending = stale ? null : await this.storage.getPending(trackId);
    if (pending && pending.points.length > 0) {
      const startsAfterTip =
        tip.lastPointMs === null || pending.t0 > tip.lastPointMs;
      if (startsAfterTip) {
        recovered = await recorder.adoptPending(pending);
      } else {
        // Points that predate the sealed tip would break check 3's strict
        // monotonicity — they are a stale write, not recoverable data.
        await this.storage.deletePending(trackId);
      }
    }

    return {
      recorder,
      continued: usable.length > 0,
      freshChain: usable.length === 0,
      keySource,
      recovered,
      tip: recovered ? recorder.info() : tip,
    };
  }

  async listTrackIds(): Promise<string[]> {
    const rides = await this.storage.listRides();
    return rides.map((r) => r.trackId);
  }

  deleteRide(trackId: string): Promise<void> {
    return this.storage.deleteRide(trackId);
  }
}

function tipFields(tip: TrackTip): Pick<
  StoredTrackRide,
  "nextSeq" | "prevJwsHash" | "chainHash" | "batchCount" | "waypointCount" | "lastPointMs"
> {
  return {
    nextSeq: tip.nextSeq,
    prevJwsHash: tip.prevJwsHash,
    chainHash: tip.chainHash,
    batchCount: tip.batchCount,
    waypointCount: tip.waypointCount,
    lastPointMs: tip.lastPointMs,
  };
}

function batchesMatchNonce(
  batches: readonly StoredTrackBatch[],
  nonce: string,
): boolean {
  try {
    return decodeTrackBatch(batches[0].jws).non === nonce;
  } catch {
    return false;
  }
}

/** Derive the chain tip from the sealed batches — the store that gets
 *  uploaded, and therefore the authority. The ride record's mirrored tip is
 *  only used to answer "what is H_-1" when nothing is sealed yet. */
function tipFromBatches(
  trackId: string,
  batches: readonly StoredTrackBatch[],
  ride: StoredTrackRide | null,
  pending: StoredPendingBatch | null,
): TrackTip {
  if (batches.length === 0) {
    return {
      trackId,
      nextSeq: 0,
      prevJwsHash: "",
      chainHash: ride?.chainHash ?? "",
      batchCount: 0,
      waypointCount: 0,
      pendingCount: pending?.points.length ?? 0,
      lastPointMs: pending?.lastPointMs ?? null,
    };
  }
  const last = batches[batches.length - 1];
  return {
    trackId,
    nextSeq: last.seq + 1,
    prevJwsHash: last.jwsHash,
    chainHash: last.chainHash,
    batchCount: batches.length,
    waypointCount: batches.reduce((n, b) => n + b.count, 0),
    pendingCount: pending?.points.length ?? 0,
    lastPointMs: pending ? Math.max(last.t1, pending.lastPointMs) : last.t1,
  };
}

/** Open the local track store. Never throws for a missing or hostile
 *  IndexedDB: it degrades to memory and reports it through `durable` /
 *  `warning` so the UI can show `TRACK_FALLBACK_WARNING`. */
export async function openTrackStore(
  opts: TrackStoreOptions = {},
): Promise<TrackStore> {
  if (opts.storage) {
    // Keep the UI invariant honest: `durable === false` always comes with a
    // warning, even for an injected adapter.
    return new TrackStoreImpl(
      opts.storage,
      opts.storage.durable ? null : "no_indexeddb",
      opts,
    );
  }
  const factory =
    opts.indexedDBFactory !== undefined
      ? opts.indexedDBFactory
      : ((globalThis as { indexedDB?: IDBFactory }).indexedDB ?? null);
  if (!factory) {
    return new TrackStoreImpl(new MemoryTrackStorage(), "no_indexeddb", opts);
  }
  try {
    const storage = await IdbTrackStorage.open(factory);
    return new TrackStoreImpl(storage, null, opts);
  } catch {
    return new TrackStoreImpl(
      new MemoryTrackStorage(),
      "indexeddb_failed",
      opts,
    );
  }
}
